- name: apt update
  apt:
    update_cache: yes

- name: install packages docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl

- name: download 
  get_url: 
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
